### Register User
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "name": "Test User",
  "password": "testpassword"
}

### Login User
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

### Get All Todos for a User
POST http://localhost:3000/todos
Content-Type: application/json

{
  "user_id": "5bed9686-5eaa-47b6-95ca-9797d734cd1d"
}

### Add a New Todo
POST http://localhost:3000/add-todo
Content-Type: application/json

{
  "user_id": "5bed9686-5eaa-47b6-95ca-9797d734cd1d",
  "todo": "Learn Node.js",
  "status": "completed"
}

### Update Todo Status
PUT http://localhost:3000/update-todo-status
Content-Type: application/json

{
  "todo_id": "53b47640-4bd2-4aba-b611-ca51fe2a6b05",
  "status": "progress"
}

### Start Timer for a Todo
POST http://localhost:3000/start-timer
Content-Type: application/json

{
  "todo_id": "53b47640-4bd2-4aba-b611-ca51fe2a6b05"
}

### Pause Timer for a Todo
POST http://localhost:3000/pause-timer
Content-Type: application/json

{
  "todo_id": "53b47640-4bd2-4aba-b611-ca51fe2a6b05"
}

### Reset Timer for a Todo
POST http://localhost:3000/reset-timer
Content-Type: application/json

{
  "todo_id": "53b47640-4bd2-4aba-b611-ca51fe2a6b05"
}
